substitutions:
  devicename: rego-reader
  friendly_name: "Reader Reader "
  device_description: "Rego600 reader for heat-pump communication"

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: "${device_description}"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

logger:
  level: DEBUG
  baud_rate: 0 # disable logging over uart

api:
  encryption:
    key: !secret api_key

ota:

web_server:

external_components:
  - source: github://dala318/esphome-rego600

uart:
  id: uart_bus
  baud_rate: 19200

rego600:
  uart_id: uart_bus
  id: rego600_hub
  log_all: true

binary_sensor:
  - platform: rego600
    # rego600_id: rego600_hub  # Optional if only one hub
    name: ${friendly_name}Ground loop pump P3
    rego_variable: 0x01FD

  - platform: rego600
    name: ${friendly_name}Compresor
    rego_variable: 0x01FE

  - platform: rego600
    name: ${friendly_name}Additional heat 3kW
    rego_variable: 0x01FF

  - platform: rego600
    name: ${friendly_name}Additional heat 6kW
    rego_variable: 0x0200

  - platform: rego600
    name: ${friendly_name}Radiator pump P1
    rego_variable: 0x0203

  - platform: rego600
    name: ${friendly_name}Heat carrier pump P2
    rego_variable: 0x0204

  - platform: rego600
    name: ${friendly_name}Tree-way valve VXV
    rego_variable: 0x0205

  - platform: rego600
    name: ${friendly_name}Alarm
    rego_variable: 0x0206

sensor:
  - platform: rego600
    name: ${friendly_name}Radiator return GT1
    rego_variable: 0x0209
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Outdoor GT2
    rego_variable: 0x020A
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Hot water GT3
    rego_variable: 0x020B
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Forward GT4
    rego_variable: 0x020C
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Room GT5
    rego_variable: 0x020D
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Compressor GT6
    rego_variable: 0x020E
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Heat fluid out GT8
    rego_variable: 0x020F
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Heat fluid in GT9
    rego_variable: 0x0210
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Cold fluid in GT10
    rego_variable: 0x0211
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}Cold fluid out GT11
    rego_variable: 0x0212
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: rego600
    name: ${friendly_name}External hot water GT3x
    rego_variable: 0x0213
    value_factor: 0.1
    unit_of_measurement: °C
    state_class: measurement
    accuracy_decimals: 1

  - platform: template
    name: Fake indoor actual temp
    id: indoor_temp
    lambda: |-
      return id(gt1_target).state;

# button:
#   - platform: rego600
#     name: External control
#     rego_variable: 0x0213

number:
  - platform: rego600
    name: ${friendly_name}GT1 Target value
    id: gt1_target
    rego_variable: 0x006E
    value_factor: 0.1
    unit_of_measurement: °C
    min_value: 0
    max_value: 100
    step: 1

  - platform: rego600
    name: ${friendly_name}GT1 On value
    rego_variable: 0x006F
    value_factor: 0.1
    unit_of_measurement: °C
    min_value: 0
    max_value: 100
    step: 1

  - platform: rego600
    name: ${friendly_name}GT1 Off value
    rego_variable: 0x0070
    value_factor: 0.1
    unit_of_measurement: °C
    min_value: 0
    max_value: 100
    step: 1

  - platform: rego600
    name: ${friendly_name}GT3 Target value
    rego_variable: 0x002B
    value_factor: 0.1
    unit_of_measurement: °C
    min_value: 0
    max_value: 100
    step: 1

  - platform: rego600
    name: ${friendly_name}GT3 On value
    rego_variable: 0x0073
    value_factor: 0.1
    unit_of_measurement: °C
    min_value: 0
    max_value: 100
    step: 1

  - platform: rego600
    name: ${friendly_name}GT3 Off value
    rego_variable: 0x0074
    value_factor: 0.1
    unit_of_measurement: °C
    min_value: 0
    max_value: 100
    step: 1

  - platform: rego600
    name: ${friendly_name}GT4 Target value
    rego_variable: 0x006D
    value_factor: 0.1
    unit_of_measurement: °C
    min_value: 0
    max_value: 100
    step: 1

  - platform: rego600
    name: ${friendly_name}Add heat power in %
    rego_variable: 0x
    value_factor: 0.1
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1

# climate:
#   - platform: rego600
#     name: House temp
#     rego_variable: 0x0010
#     sensor_id: indoor_temp

# switch:
#   - platform: rego600
#     name: ${friendly_name}
#     rego_variable: 

# text_sensor:
#   - platform: rego600
#     name: ${friendly_name}
#     rego_variable: 
